BEGIN {
S["am__EXEEXT_FALSE"]=""
S["am__EXEEXT_TRUE"]="#"
S["LTLIBOBJS"]=""
S["LIBOBJS"]=""
S["CONFIGURE_INVOCATION"]="./configure  '--prefix=/home/jcgoodru/Desktop/fastjet/fjparallel/fastjet-3.0.6/../fastjet-install' 'CXXFLAGS=-std=c++11' 'LIBS=-lpthread'"
S["CONFIG_SUMMARY"]="Configuration summary:\\n----------------------\\n  Installation directory     /home/jcgoodru/Desktop/fastjet/fjparallel/fastjet-3.0.6/../fastjet-inst"\
"all\\n  Shared libraries           yes\\n  Static libraries           yes\\n  Debug flag                 yes\\n  CGAL support               no\\n  Plugin"\
"s: EECambridge       yes\\n           Jade              yes\\n           NestedDefs        yes\\n           SISCone           yes\\n           CDFCones "\
"         yes\\n           D0RunICone        no\\n           D0RunIICone       no\\n           ATLASCone         no\\n           CMSIterativeCone  no\\n  "\
"         PxCone            no\\n           TrackJet          no\\n           GridJet           yes\\n  Monolithic plugins lib     yes\\n"
S["LIST_ALL_PLUGINS"]=" SISCone CDFCones NestedDefs EECambridge Jade GridJet"
S["CONFIG_LIBS"]=" -lm "
S["CONFIG_CXXFLAGS"]=""
S["CONFIG_LIBS_PLUGINS_STATIC"]=" ${installationdir}/lib/libfastjetplugins.a  ${installationdir}/lib/libsiscone.a ${installationdir}/lib/libsiscone_spherical.a"
S["CONFIG_LIBS_PLUGINS"]=" -lfastjetplugins  -lsiscone_spherical -lsiscone"
S["D0_CXXFLAGS"]=""
S["AM_FCFLAGS"]=""
S["AM_FFLAGS"]=""
S["F77"]=""
S["FLIBS"]=""
S["FFLAGS"]=""
S["FCLIBS"]=""
S["ac_ct_FC"]=""
S["FCFLAGS"]=""
S["FC"]=""
S["OTOOL64"]=""
S["OTOOL"]=""
S["LIPO"]=""
S["NMEDIT"]=""
S["DSYMUTIL"]=""
S["lt_ECHO"]="echo"
S["RANLIB"]="ranlib"
S["AR"]="ar"
S["OBJDUMP"]="objdump"
S["NM"]="/usr/bin/nm -B"
S["ac_ct_DUMPBIN"]=""
S["DUMPBIN"]=""
S["LD"]="/usr/bin/ld"
S["FGREP"]="/bin/grep -F"
S["host_os"]="linux-gnu"
S["host_vendor"]="pc"
S["host_cpu"]="i686"
S["host"]="i686-pc-linux-gnu"
S["build_os"]="linux-gnu"
S["build_vendor"]="pc"
S["build_cpu"]="i686"
S["build"]="i686-pc-linux-gnu"
S["LIBTOOL"]="$(SHELL) $(top_builddir)/libtool"
S["BUILD_PLUGIN_GRIDJET_FALSE"]="#"
S["BUILD_PLUGIN_GRIDJET_TRUE"]=""
S["BUILD_PLUGIN_D0RUNICONE_FALSE"]=""
S["BUILD_PLUGIN_D0RUNICONE_TRUE"]="#"
S["BUILD_PLUGIN_JADE_FALSE"]="#"
S["BUILD_PLUGIN_JADE_TRUE"]=""
S["BUILD_PLUGIN_EECAMBRIDGE_FALSE"]="#"
S["BUILD_PLUGIN_EECAMBRIDGE_TRUE"]=""
S["BUILD_PLUGIN_CMSITERATIVECONE_FALSE"]=""
S["BUILD_PLUGIN_CMSITERATIVECONE_TRUE"]="#"
S["BUILD_PLUGIN_ATLASCONE_FALSE"]=""
S["BUILD_PLUGIN_ATLASCONE_TRUE"]="#"
S["BUILD_PLUGIN_TRACKJET_FALSE"]=""
S["BUILD_PLUGIN_TRACKJET_TRUE"]="#"
S["BUILD_PLUGIN_NESTEDDEFS_FALSE"]="#"
S["BUILD_PLUGIN_NESTEDDEFS_TRUE"]=""
S["BUILD_PLUGIN_D0RUNIICONE_FALSE"]=""
S["BUILD_PLUGIN_D0RUNIICONE_TRUE"]="#"
S["BUILD_PLUGIN_PXCONE_FALSE"]=""
S["BUILD_PLUGIN_PXCONE_TRUE"]="#"
S["BUILD_PLUGIN_CDFCONES_FALSE"]="#"
S["BUILD_PLUGIN_CDFCONES_TRUE"]=""
S["subdirs"]=" plugins/SISCone/siscone"
S["BUILD_PLUGIN_SISCONE_FALSE"]="#"
S["BUILD_PLUGIN_SISCONE_TRUE"]=""
S["MONOLITHIC_PLUGINS_FALSE"]="#"
S["MONOLITHIC_PLUGINS_TRUE"]=""
S["HAS_SHARED"]="yes"
S["AM_CXXFLAGS"]=" -g  -Woverloaded-virtual  -DDROP_CGAL "
S["CONFIG_RUNPATH_FLAGS"]="-Wl,--enable-new-dtags"
S["HAS_RUNPATH_SUPPORT"]="yes"
S["CGAL_LIBS"]=""
S["CGAL_CPPFLAGS"]=""
S["CXXCPP"]="g++ -E"
S["SED"]="/bin/sed"
S["LN_S"]="ln -s"
S["cxx_found"]="yes"
S["am__fastdepCXX_FALSE"]="#"
S["am__fastdepCXX_TRUE"]=""
S["CXXDEPMODE"]="depmode=gcc3"
S["ac_ct_CXX"]="g++"
S["CXXFLAGS"]="-std=c++11"
S["CXX"]="g++"
S["EGREP"]="/bin/grep -E"
S["GREP"]="/bin/grep"
S["CPP"]="gcc -E"
S["am__fastdepCC_FALSE"]="#"
S["am__fastdepCC_TRUE"]=""
S["CCDEPMODE"]="depmode=gcc3"
S["AMDEPBACKSLASH"]="\\"
S["AMDEP_FALSE"]="#"
S["AMDEP_TRUE"]=""
S["am__quote"]=""
S["am__include"]="include"
S["DEPDIR"]=".deps"
S["OBJEXT"]="o"
S["EXEEXT"]=""
S["ac_ct_CC"]="gcc"
S["CPPFLAGS"]=""
S["LDFLAGS"]=""
S["CFLAGS"]="-g -O2"
S["CC"]="gcc"
S["am__untar"]="tar -xf -"
S["am__tar"]="tar --format=ustar -chf - \"$$tardir\""
S["AMTAR"]="${SHELL} /home/jcgoodru/Desktop/fastjet/fjparallel/fastjet-3.0.6/missing --run tar"
S["am__leading_dot"]="."
S["SET_MAKE"]=""
S["AWK"]="mawk"
S["mkdir_p"]="/bin/mkdir -p"
S["MKDIR_P"]="/bin/mkdir -p"
S["INSTALL_STRIP_PROGRAM"]="$(install_sh) -c -s"
S["STRIP"]="strip"
S["install_sh"]="${SHELL} /home/jcgoodru/Desktop/fastjet/fjparallel/fastjet-3.0.6/install-sh"
S["MAKEINFO"]="${SHELL} /home/jcgoodru/Desktop/fastjet/fjparallel/fastjet-3.0.6/missing --run makeinfo"
S["AUTOHEADER"]="${SHELL} /home/jcgoodru/Desktop/fastjet/fjparallel/fastjet-3.0.6/missing --run autoheader"
S["AUTOMAKE"]="${SHELL} /home/jcgoodru/Desktop/fastjet/fjparallel/fastjet-3.0.6/missing --run automake-1.11"
S["AUTOCONF"]="${SHELL} /home/jcgoodru/Desktop/fastjet/fjparallel/fastjet-3.0.6/missing --run autoconf"
S["ACLOCAL"]="${SHELL} /home/jcgoodru/Desktop/fastjet/fjparallel/fastjet-3.0.6/missing --run aclocal-1.11"
S["VERSION"]="3.0.6"
S["PACKAGE"]="fastjet"
S["CYGPATH_W"]="echo"
S["am__isrc"]=""
S["INSTALL_DATA"]="${INSTALL} -m 644"
S["INSTALL_SCRIPT"]="${INSTALL}"
S["INSTALL_PROGRAM"]="${INSTALL}"
S["target_alias"]=""
S["host_alias"]=""
S["build_alias"]=""
S["LIBS"]="-lm -lpthread"
S["ECHO_T"]=""
S["ECHO_N"]="-n"
S["ECHO_C"]=""
S["DEFS"]="-DHAVE_CONFIG_H"
S["mandir"]="${datarootdir}/man"
S["localedir"]="${datarootdir}/locale"
S["libdir"]="${exec_prefix}/lib"
S["psdir"]="${docdir}"
S["pdfdir"]="${docdir}"
S["dvidir"]="${docdir}"
S["htmldir"]="${docdir}"
S["infodir"]="${datarootdir}/info"
S["docdir"]="${datarootdir}/doc/${PACKAGE_TARNAME}"
S["oldincludedir"]="/usr/include"
S["includedir"]="${prefix}/include"
S["localstatedir"]="${prefix}/var"
S["sharedstatedir"]="${prefix}/com"
S["sysconfdir"]="${prefix}/etc"
S["datadir"]="${datarootdir}"
S["datarootdir"]="${prefix}/share"
S["libexecdir"]="${exec_prefix}/libexec"
S["sbindir"]="${exec_prefix}/sbin"
S["bindir"]="${exec_prefix}/bin"
S["program_transform_name"]="s,x,x,"
S["prefix"]="/home/jcgoodru/Desktop/fastjet/fjparallel/fastjet-3.0.6/../fastjet-install"
S["exec_prefix"]="${prefix}"
S["PACKAGE_BUGREPORT"]=""
S["PACKAGE_STRING"]="FastJet 3.0.6"
S["PACKAGE_VERSION"]="3.0.6"
S["PACKAGE_TARNAME"]="fastjet"
S["PACKAGE_NAME"]="FastJet"
S["PATH_SEPARATOR"]=":"
S["SHELL"]="/bin/bash"
  for (key in S) S_is_set[key] = 1
  FS = ""

}
{
  line = $ 0
  nfields = split(line, field, "@")
  substed = 0
  len = length(field[1])
  for (i = 2; i < nfields; i++) {
    key = field[i]
    keylen = length(key)
    if (S_is_set[key]) {
      value = S[key]
      line = substr(line, 1, len) "" value "" substr(line, len + keylen + 3)
      len += length(value) + length(field[++i])
      substed = 1
    } else
      len += 1 + keylen
  }

  print line
}

